# Generated by Django 6.0.1 on 2026-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Uncompleted'), (1, 'Completed'), (2, 'Dumped')], default=0)),
            ],
        ),
    ]
