# Generated by Django 6.0.1 on 2026-01-18 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date_of_completion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasks',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
